# Generated by Django 5.2.7 on 2025-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
